version: '3'

vars:
  FILE: graph
  PROGRAM_GRAPH: program
  SITE_GRAPH: site
  CMEM: aksw.eccenca.dev
  WORKFLOW: 54b8da6d-1c3b-4c84-9268-3e456165b9ad_Programm:238cc3fb-389b-439c-9b7b-d492305db2d3_ProgrammTransformation
  PROGRAM_GRAPH_IRI: https://dataweek.de/programm

tasks:

  default:
    cmds:
      - task: normalize_turtle
      - task: get_program
      - task: sync_sources_to_site
      - task: styles
      - task: build_de
      - task: build_en

  serve:
    cmds:
      - python -m http.server --directory _site

  styles:
    cmds:
      - npx webpack

  build_de:
    cmds:
      - bundle exec jekyll build -d _site
    env:
      JEKYLL_LANGUAGE: de

  build_en:
    cmds:
      - bundle exec jekyll build -d _site/en
    env:
      JEKYLL_LANGUAGE: en

  sync_clean:
    cmds:
      - task: sync_sources_to_site

  sync_sources_to_site:
    cmds:
      - rapper -i turtle -o ntriples {{.FILE}}.ttl | LC_ALL=C sort -u > {{.FILE}}.nt
      - cat {{.FILE}}.nt {{.PROGRAM_GRAPH}}.nt | LC_ALL=C sort -u > {{.SITE_GRAPH}}.nt

  get_program:
    - cmemc -c {{.CMEM}} workflow execute --wait {{.WORKFLOW}}
    - cmemc -c {{.CMEM}} graph export {{.PROGRAM_GRAPH_IRI}} | LC_ALL=C sort -u > {{.PROGRAM_GRAPH}}.nt

  normalize_turtle:
    cmds:
      - |
        rapper -i turtle -o turtle \
          -f 'xmlns:xsd="http://www.w3.org/2001/XMLSchema#"' \
          -f 'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"' \
          -f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' \
          -f 'xmlns:owl="http://www.w3.org/2002/07/owl#"' \
          -f 'xmlns:dct="http://purl.org/dc/terms/"' \
          -f 'xmlns:skos="http://www.w3.org/2004/02/skos/core#"' \
          -f 'xmlns:schema="http://schema.org/"' \
          -f 'xmlns:foaf="http://xmlns.com/foaf/0.1/"' \
          -f 'xmlns:ecc-ns="https://ns.eccenca.com/"' \
          -f 'xmlns:site="http://ns.ontowiki.net/SysOnt/Site/"' \
          -f 'xmlns:aksw="http://aksw.org/"' \
          -f 'xmlns:dw="https://dataweek.de/#"' \
          {{.FILE}}.ttl | sponge {{.FILE}}.ttl
