version: '3'

vars:
  FILE: graph

tasks:

  default:
    cmds:
      - task: normalize_turtle
      - task: sync_turtle_to_nt
      - task: styles
      - task: build_de
      - task: build_en

  serve:
    cmds:
      - python -m http.server --directory _site

  styles:
    cmds:
      - npx webpack

  build_de:
    cmds:
      - bundle exec jekyll build -d _site
    env:
      JEKYLL_LANGUAGE: de

  build_en:
    cmds:
      - bundle exec jekyll build -d _site/en
    env:
      JEKYLL_LANGUAGE: en

  sync_clean:
    cmds:
      - task: graph_clean
      - task: sync_turtle_to_nt

  graph_clean:
    cmds:
      - git restore graph.nt

  sync_turtle_to_nt:
    cmds:
      - |
        git status --porcelain graph.nt | grep '^.[MTD]' && echo "ABORT SYNC: graph.nt has unstaged changes." ||
        rapper -i turtle -o ntriples {{.FILE}}.ttl | LC_ALL=C sort -u > {{.FILE}}.nt

  normalize_turtle:
    cmds:
      - |
        rapper -i turtle -o turtle \
          -f 'xmlns:xsd="http://www.w3.org/2001/XMLSchema#"' \
          -f 'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"' \
          -f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' \
          -f 'xmlns:owl="http://www.w3.org/2002/07/owl#"' \
          -f 'xmlns:dct="http://purl.org/dc/terms/"' \
          -f 'xmlns:skos="http://www.w3.org/2004/02/skos/core#"' \
          -f 'xmlns:schema="http://schema.org/"' \
          -f 'xmlns:foaf="http://xmlns.com/foaf/0.1/"' \
          -f 'xmlns:ecc-ns="https://ns.eccenca.com/"' \
          -f 'xmlns:site="http://ns.ontowiki.net/SysOnt/Site/"' \
          -f 'xmlns:aksw="http://aksw.org/"' \
          -f 'xmlns:dw="https://dataweek.de/#"' \
          {{.FILE}}.ttl | sponge {{.FILE}}.ttl
