# Site settings
title: Data Week
email: dataweek@infai.org
baseurl: ""
url: "https://2023.dataweek.de"
rootResource: "<https://2023.dataweek.de/>"
translations:
  de: "<https://2023.dataweek.de/>"
  en: "<https://2023.dataweek.de/en/>"
language: de
twitter_username: DataWeekLeipzig

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-rdf

exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - todo.md
  - Taskfile.yml
  - README.md
  - docu

jekyll_rdf:
  path: "graph.nt"
  restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"dataweek.de\") }"
  default_template: default.html
  class_template_mappings:
#    "http://xmlns.com/foaf/0.1/Document" : "basic.html"
    "http://schema.org/Event" : "event.html"
