# Site settings
title: Data Week Leipzig 2024
email: dataweek@infai.org
baseurl: ""
url: "https://2024.dataweek.de"
rootResource: "<https://2024.dataweek.de/>"
translations:
  de: "<https://2024.dataweek.de/>"
  en: "<https://2024.dataweek.de/en/>"
language: de
twitter_username: DataWeekLeipzig

stream_1_1: "!dFHhDmvNTjsDdFleJx:matrix.org" # Menschen vernetzen - Daten nutzen
stream_1_2: "!irnMvwCKJtUyHjAAwI:matrix.org" # Data Science Mania
stream_2_1: "!UPyDoiPIBTThTPDQXF:matrix.org" # Kommunen für Kommunen 1 (Sitzungssaal)
stream_2_2: "!LXXKyxfLmjTtRTzzAc:matrix.org" # Kommunen für Kommunen 2 (Festsaal)
stream_3_1: "!wGwIOvxQCUcVwiKPQk:matrix.org" # Urban Data Summit
stream_4_1: "!pEreTkmeqwWZPtAWpA:matrix.org" # LSWT

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-rdf

exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - todo.md
  - Taskfile.yml
  - README.md
  - docu

jekyll_rdf:
  #path: "graph.ttl"
  path: ".model/event.ttl"
  restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"^https://2024.dataweek.de\") }"
  default_template: default.html
  class_template_mappings:
    "https://dataweek.de/#ProgramView" : "program_view.html"
    "https://dataweek.de/#MovedResource" : "moved.html"
    "http://schema.org/Event" : "event.html"
