# Site settings
title: Data Week Leipzig 2026
email: dataweek@infai.org
baseurl: ""
url: "https://2026.dataweek.de"
rootResource: "<https://2026.dataweek.de/>"
translations:
  de: "<https://2026.dataweek.de/>"
  en: "<https://2026.dataweek.de/en/>"
language: de
twitter_username: DataWeekLeipzig

stream_1_1: "!slhYXYesrqRvWAMjJX:matrix.org" # Sensoren, Satelliten & Stadtentwicklung
stream_1_2: "!MwGlqKJVHWMjNrFgxD:matrix.org" # Stadt, Daten & KI
stream_2_1: "!DeBYSgyrflSrpYyZJO:matrix.org" # Stadt, Digital & Lebenswert
stream_2_2: "!ANIrWpElchEVitpnLm:matrix.org" # Menschen, Daten & Energie
stream_3_1: "!rjAKHGWSkSCKciTDeI:matrix.org" # LSWT2025
stream_3_2: "!txjyhLUdhislnmvCBx:matrix.org" # AIAMOroadshow

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-rdf

exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - todo.md
  - Taskfile.yml
  - README.md
  - docu

jekyll_rdf:
  path: "graph.nt"
  restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"^https://2026.dataweek.de\") }"
  default_template: default.html
  class_template_mappings:
    "https://dataweek.de/#ProgramView" : "program_view.html"
    "https://dataweek.de/#MovedResource" : "moved.html"
    "http://schema.org/Event" : "event.html"
