version: '3'

vars:
  PAGE_GRAPH: graph
  PROGRAM_GRAPH: program
  SITE_GRAPH: site
  CMEM: aksw.eccenca.dev
  WORKFLOW: 54b8da6d-1c3b-4c84-9268-3e456165b9ad_Programm:238cc3fb-389b-439c-9b7b-d492305db2d3_ProgrammTransformation
  PAGE_GRAPH_IRI: https://dataweek.de/
  PROGRAM_GRAPH_IRI: https://dataweek.de/programm
  GIT_USER_NAME: DataWeek CMEM Update Bot 🤖
  GIT_USER_EMAIL: dw-cmem-update-bot@example.org
  GIT_COMMIT_MESSAGE: Update from CMEM
  WORKING_DIRECTORY: '{{.github.workspace | default .PWD}}'
  CMEMC_VERSION: v21.11.4
  CMEMC_IMAGE: docker-registry.eccenca.com/eccenca-cmemc:{{.CMEMC_VERSION}}
  CMEMC_DOCKER: docker run -i --rm -e "CMEM_BASE_URI=https://aksw.eccenca.dev/" -e "OAUTH_CLIENT_SECRET={{.OAUTH_CLIENT_SECRET}}" -v {{.WORKING_DIRECTORY}}:/data {{.CMEMC_IMAGE}}
  CMEMC: '{{.CMEMC_LOCAL | default .CMEMC_DOCKER}}'
  ID_UID:
    sh: id -u
  ID_GID:
    sh: id -g
  JEKYLL_UID: '{{.JEKYLL_UID | default .ID_UID}}'
  JEKYLL_GID: '{{.JEKYLL_GID | default .ID_GID}}'
  JEKYLL_IMAGE: jekyll-rdf:develop
  LANGUAGE: '{{.LANGUAGE | default "de"}}'
  TARGET: '{{.TARGET | default "_site"}}'
  TARGET_DE: '{{.TARGET_DE | default .TARGET}}'
  TARGET_EN: '{{.TARGET_EN | default "_site/en"}}'

tasks:

  default:
    desc: List all tasks
    cmds:
      - task -a

  build:
    desc: Build the page locally
    cmds:
      - task: helper:normalize-turtle
      - task: sync:get-program
      - task: sync:clean
      - task: build:de
      - task: build:en

  ci:
    desc: Build tasks for the CI
    cmds:
      - task: build:de:docker
      - task: build:en:docker

  ci:data-sync:
    desc: Synchronize the data in the CI
    cmds:
      - task: sync:get-program
      - task: sync:upload-page-graph
      - task: sync:merge-site-graph
      - task: track:commit-and-push-data

  serve:
    desc: Serve the locally built site
    cmds:
      - python -m http.server --directory {{.TARGET}}

  build:de:
    cmds:
      - bundle exec jekyll build -d {{.TARGET_DE}}
    env:
      JEKYLL_LANGUAGE: de

  build:en:
    cmds:
      - bundle exec jekyll build -d {{.TARGET_EN}}
    env:
      JEKYLL_LANGUAGE: en

  build:de:docker:
    cmds:
      - task: build:docker
        vars:
          LANGUAGE: de
          TARGET: '{{.TARGET_DE}}'

  build:en:docker:
    cmds:
      - task: build:docker
        vars:
          LANGUAGE: en
          TARGET: '{{.TARGET_EN}}'

  build:docker:
    - |
      docker run --rm \
      --workdir /github/workspace \
      -v {{.WORKING_DIRECTORY}}:/github/workspace \
      -e TZ=Europe/Berlin -e JEKYLL_UID="{{.JEKYLL_UID}}" -e JEKYLL_GID="{{.JEKYLL_GID}}" -e JEKYLL_LANGUAGE={{.LANGUAGE}} \
      {{.JEKYLL_IMAGE}} jekyll build -d {{.TARGET}}

  sync:clean:
    - rapper -i turtle -o ntriples {{.PAGE_GRAPH}}.ttl | LC_ALL=C sort -u > {{.PAGE_GRAPH}}.nt
    - task: sync:merge-site-graph

  sync:merge-site-graph:
    - cat {{.PAGE_GRAPH}}.nt {{.PROGRAM_GRAPH}}.nt | LC_ALL=C sort -u > {{.SITE_GRAPH}}.nt

  sync:get-program:
    - '{{.CMEMC}} workflow execute --wait {{.WORKFLOW}}'
    - '{{.CMEMC}} graph export {{.PROGRAM_GRAPH_IRI}} | LC_ALL=C sort -u > {{.PROGRAM_GRAPH}}.nt'

  sync:upload-page-graph:
    - '{{.CMEMC}} graph import --replace {{.PAGE_GRAPH}}.ttl {{.PAGE_GRAPH_IRI}}'

  track:commit-and-push-data:
    - |
      git add {{.SITE_GRAPH}}.nt {{.PROGRAM_GRAPH}}.nt
      git -c user.name "{{.GIT_USER_NAME}}" -c user.email "{{.GIT_USER_EMAIL}}" commit -m "{{.GIT_COMMIT_MESSAGE}}" || echo ""
      git push || echo ""

  helper:normalize-turtle:
    - |
      rapper -i turtle -o turtle \
        -f 'xmlns:xsd="http://www.w3.org/2001/XMLSchema#"' \
        -f 'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"' \
        -f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' \
        -f 'xmlns:owl="http://www.w3.org/2002/07/owl#"' \
        -f 'xmlns:dct="http://purl.org/dc/terms/"' \
        -f 'xmlns:skos="http://www.w3.org/2004/02/skos/core#"' \
        -f 'xmlns:schema="http://schema.org/"' \
        -f 'xmlns:foaf="http://xmlns.com/foaf/0.1/"' \
        -f 'xmlns:ecc-ns="https://ns.eccenca.com/"' \
        -f 'xmlns:site="http://ns.ontowiki.net/SysOnt/Site/"' \
        -f 'xmlns:orp="https://www.openresearch.org/wiki/Property:"' \
        -f 'xmlns:aksw="http://aksw.org/"' \
        -f 'xmlns:dw="https://dataweek.de/#"' \
        -f 'xmlns:gnd="https://d-nb.info/standards/elementset/gnd#"' \
        {{.PAGE_GRAPH}}.ttl | sponge {{.PAGE_GRAPH}}.ttl
