version: '3'

vars:
  FILE: graph

tasks:
  styles:
    cmds:
      - npx webpack

  build:
    cmds:
      - bundle exec jekyll build

  sync_turtle_to_nt:
    cmds:
      - rapper -i turtle -o ntriples {{.FILE}}.ttl | LC_ALL=C sort -u > {{.FILE}}.nt

  normalize_turtle:
    cmds:
      - |
        rapper -i turtle -o turtle \
          -f 'xmlns:xsd="http://www.w3.org/2001/XMLSchema#"' \
          -f 'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"' \
          -f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' \
          -f 'xmlns:dct="http://purl.org/dc/terms/"' \
          -f 'xmlns:owl="http://www.w3.org/2002/07/owl#"' \
          -f 'xmlns:schema="http://schema.org/"' \
          -f 'xmlns:foaf="http://xmlns.com/foaf/0.1/"' \
          -f 'xmlns:ecc-ns="https://ns.eccenca.com/"' \
          -f 'xmlns:site="http://ns.ontowiki.net/SysOnt/Site/"' \
          {{.FILE}}.ttl | sponge {{.FILE}}.ttl
