# Build Jekyll Page and publish it to GitHub Pages
name: Build Jekyll Page (2023)

on:
  push:
    branches: [ past/2023 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check out Site Repository 📄
      uses: actions/checkout@v3
    - name: Run CI Tasks ⚙️
      run: task build
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: page-2023  # default: gh-pages
